tap "kaplanelad/tap", trusted: true
tap "nodenv/nodenv", trusted: true

brew "zsh"
brew "trash"
brew "vim"
brew "watch"
brew "ncdu"
brew "fzf"
brew "eza"
brew "jq"
brew "ripgrep"
brew "bat"
brew "terminal-notifier"
brew "starship"
brew "shellfirm"

brew "coreutils"
brew "git"
brew "tig"
brew "diff-so-fancy"
brew "gnupg"
brew "pinentry-mac"

brew "yarn"
brew "nodenv"
brew "nodenv/nodenv/nodenv-nvmrc"

brew "awscli"
brew "sbt"
brew "pyenv"
brew "jenv"
brew "direnv"
brew "gh"

cask "linearmouse"
cask "rectangle"
cask "hammerspoon"
cask "zulu"
cask "slack"
cask "docker"
cask "1password"
cask "ghostty"
cask "alfred"
cask "google-chrome"
cask "firefox"
cask "obs"
cask "vlc"
cask "tableplus"
cask "postman"
cask "spotify"

cask "visual-studio-code"
vscode "streetsidesoftware.code-spell-checker"
